-- ============================================================
-- DDL Oracle - Framework de Qualidade de Dados - Sefaz-CE
-- Origem: issues_metadados_cadastro_20260428_1548.xlsx
-- Convenção de prefixos aplicada:
--   COD_  Identificadores e códigos
--   NOM_  Nomes
--   DSC_  Descrições e textos curtos (VARCHAR2)
--   TXT_  Textos longos (VARCHAR2 > 500 chars)
--   NUM_  Valores numéricos
--   DAT_  Datas e timestamps
--   SIT_  Flags e situações (CHAR(1) Y/N)
--   TIP_  Tipos e categorias
--   STA_  Status
-- Limite de nome de coluna: 30 caracteres (todos validados)
-- Booleanos: CHAR(1) CHECK IN ('Y','N') - Oracle < 23c
-- ============================================================


-- ----------------------------------------------------------
-- 0. DQ_EXECUTION
--    Registra cada rodada do framework. Todas as demais
--    tabelas referenciam COD_EXECUTION para histórico
--    e comparação entre execuções.
-- ----------------------------------------------------------
CREATE TABLE DQ_EXECUTION (
    COD_EXECUTION  NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    DSC_OWNER      VARCHAR2(128)   NOT NULL,
    TIP_SOURCE     VARCHAR2(20)    NOT NULL,
    -- TIP_SOURCE: CSV | ORACLE | S3
    STA_EXECUTION  VARCHAR2(20)    NOT NULL,
    -- STA_EXECUTION: RUNNING | SUCCESS | ERROR
    DAT_EXECUTION  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    DAT_FINISHED   TIMESTAMP,
    TXT_NOTES      VARCHAR2(4000),

    CONSTRAINT PK_EXEC PRIMARY KEY (COD_EXECUTION),
    CONSTRAINT CK_EXEC_SOURCE
        CHECK (TIP_SOURCE IN ('CSV','ORACLE','S3')),
    CONSTRAINT CK_EXEC_STATUS
        CHECK (STA_EXECUTION IN ('RUNNING','SUCCESS','ERROR'))
);

COMMENT ON TABLE  DQ_EXECUTION               IS 'Registro de cada execucao do framework de qualidade de dados.';
COMMENT ON COLUMN DQ_EXECUTION.COD_EXECUTION IS 'Identificador unico da execucao (PK surrogate).';
COMMENT ON COLUMN DQ_EXECUTION.DSC_OWNER     IS 'Schema Oracle avaliado na execucao.';
COMMENT ON COLUMN DQ_EXECUTION.TIP_SOURCE    IS 'Tipo da fonte de entrada: CSV, ORACLE ou S3.';
COMMENT ON COLUMN DQ_EXECUTION.STA_EXECUTION IS 'Status da execucao: RUNNING, SUCCESS ou ERROR.';
COMMENT ON COLUMN DQ_EXECUTION.DAT_EXECUTION IS 'Data e hora de inicio da execucao.';
COMMENT ON COLUMN DQ_EXECUTION.DAT_FINISHED  IS 'Data e hora de termino da execucao.';
COMMENT ON COLUMN DQ_EXECUTION.TXT_NOTES     IS 'Observacoes livres sobre a execucao.';


-- ----------------------------------------------------------
-- 1. DQ_SCHEMA_METADATA
--    Aba SCHEMA_METADATA.
--    Uma linha por coluna de cada tabela do schema avaliado,
--    enriquecida com candidatos a metricas de conformidade
--    de formato e de redundancia.
-- ----------------------------------------------------------
CREATE TABLE DQ_SCHEMA_METADATA (
    COD_ID                 NUMBER        GENERATED BY DEFAULT AS IDENTITY,
    COD_EXECUTION          NUMBER        NOT NULL,
    DSC_OWNER              VARCHAR2(128) NOT NULL,
    NOM_TABLE              VARCHAR2(128) NOT NULL,
    NOM_COLUMN             VARCHAR2(128) NOT NULL,
    TIP_DATA               VARCHAR2(50),
    TXT_COL_COMMENTS       VARCHAR2(4000),
    TXT_TAB_COMMENTS       VARCHAR2(4000),
    TXT_CONSTRAINTS        VARCHAR2(1000),
    SIT_DUPLICATED         CHAR(1)       DEFAULT 'N',
    NUM_ROWS               NUMBER(18),
    NUM_DATA_LENGTH        NUMBER(10),
    NUM_DATA_SCALE         NUMBER(10),
    NUM_AVG_COL_LEN        NUMBER(10),
    NUM_DISTINCT           NUMBER(18),
    NUM_NULLS              NUMBER(18),
    NUM_TABLE_ROWS         NUMBER(18),
    NUM_ROW_COUNT          NUMBER(18),
    SIT_NULLABLE           CHAR(1),
    SIT_DEFAULT_ON_NULL    CHAR(1),
    SIT_IS_PK              CHAR(1),
    SIT_IS_FK              CHAR(1),
    SIT_IS_UNIQUE          CHAR(1),
    NUM_NULL_PERCENT       NUMBER(6,2),
    SIT_FC_CANDIDATE       CHAR(1)       DEFAULT 'N',
    DSC_FC_METRIC          VARCHAR2(100),
    DSC_FC_DIMENSION       VARCHAR2(50),
    DSC_FC_SEMANTIC_TAG    VARCHAR2(50),
    TIP_FC_RULE            VARCHAR2(50),
    DSC_FC_EXPECTED_FORMAT VARCHAR2(500),
    DSC_FC_PRIORITY        VARCHAR2(20),
    DSC_FC_DESCRIPTION     VARCHAR2(500),
    SIT_RED_CANDIDATE      CHAR(1)       DEFAULT 'N',
    DSC_RED_METRIC         VARCHAR2(100),
    DSC_RED_DIMENSION      VARCHAR2(50),
    TIP_RED_RULE           VARCHAR2(50),
    DSC_RED_PRIORITY       VARCHAR2(20),
    DSC_RED_DESCRIPTION    VARCHAR2(500),
    DSC_RED_CALC_METHOD    VARCHAR2(100),

    CONSTRAINT PK_SM
        PRIMARY KEY (COD_ID),
    CONSTRAINT FK_SM_EXEC
        FOREIGN KEY (COD_EXECUTION) REFERENCES DQ_EXECUTION(COD_EXECUTION),
    CONSTRAINT UQ_SM_COLUMN
        UNIQUE (COD_EXECUTION, DSC_OWNER, NOM_TABLE, NOM_COLUMN),
    CONSTRAINT CK_SM_DUPLICATED
        CHECK (SIT_DUPLICATED      IN ('Y','N')),
    CONSTRAINT CK_SM_NULLABLE
        CHECK (SIT_NULLABLE        IN ('Y','N')),
    CONSTRAINT CK_SM_DEFAULT_ON_NULL
        CHECK (SIT_DEFAULT_ON_NULL IN ('Y','N')),
    CONSTRAINT CK_SM_IS_PK
        CHECK (SIT_IS_PK           IN ('Y','N')),
    CONSTRAINT CK_SM_IS_FK
        CHECK (SIT_IS_FK           IN ('Y','N')),
    CONSTRAINT CK_SM_IS_UNIQUE
        CHECK (SIT_IS_UNIQUE       IN ('Y','N')),
    CONSTRAINT CK_SM_FC_CANDIDATE
        CHECK (SIT_FC_CANDIDATE    IN ('Y','N')),
    CONSTRAINT CK_SM_RED_CANDIDATE
        CHECK (SIT_RED_CANDIDATE   IN ('Y','N'))
);

COMMENT ON TABLE  DQ_SCHEMA_METADATA                     IS 'Metadados estruturais por coluna de cada tabela do schema avaliado.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.COD_ID              IS 'Identificador unico do registro (PK surrogate).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.COD_EXECUTION       IS 'Referencia a execucao que gerou este registro.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.DSC_OWNER           IS 'Schema Oracle dono da tabela.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.NOM_TABLE           IS 'Nome da tabela.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.NOM_COLUMN          IS 'Nome da coluna.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.TIP_DATA            IS 'Tipo de dado Oracle da coluna (ex: VARCHAR2, NUMBER, DATE).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.TXT_COL_COMMENTS    IS 'Comentario registrado na coluna no Oracle.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.TXT_TAB_COMMENTS    IS 'Comentario registrado na tabela no Oracle.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.TXT_CONSTRAINTS     IS 'Lista de constraints associadas a coluna.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.SIT_DUPLICATED      IS 'Indica se a tabela possui registros duplicados (Y/N).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.NUM_ROWS            IS 'Numero de linhas segundo estatisticas do Oracle (ALL_TABLES).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.NUM_DATA_LENGTH     IS 'Tamanho definido para a coluna.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.NUM_DATA_SCALE      IS 'Escala numerica da coluna.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.NUM_AVG_COL_LEN     IS 'Comprimento medio dos valores na coluna.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.NUM_DISTINCT        IS 'Numero de valores distintos na coluna.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.NUM_NULLS           IS 'Numero de valores nulos na coluna.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.NUM_TABLE_ROWS      IS 'Contagem de linhas via ALL_TAB_STATISTICS.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.NUM_ROW_COUNT       IS 'Contagem de linhas via COUNT(*).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.SIT_NULLABLE        IS 'Indica se a coluna aceita nulos (Y/N).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.SIT_DEFAULT_ON_NULL IS 'Indica se ha valor default para nulos (Y/N).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.SIT_IS_PK           IS 'Indica se a coluna faz parte de uma PK (Y/N).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.SIT_IS_FK           IS 'Indica se a coluna faz parte de uma FK (Y/N).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.SIT_IS_UNIQUE       IS 'Indica se a coluna possui constraint UNIQUE (Y/N).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.NUM_NULL_PERCENT    IS 'Percentual de valores nulos na coluna.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.SIT_FC_CANDIDATE    IS 'Candidata a metrica de conformidade de formato (Y/N).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.DSC_FC_METRIC       IS 'Nome da metrica de conformidade de formato aplicavel.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.DSC_FC_DIMENSION    IS 'Dimensao de qualidade da metrica de conformidade.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.DSC_FC_SEMANTIC_TAG IS 'Tag semantica detectada (ex: CPF, EMAIL, CEP, DAT).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.TIP_FC_RULE         IS 'Tipo de regra de conformidade (ex: regex, date_string).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.DSC_FC_EXPECTED_FORMAT IS 'Padrao esperado (expressao regular ou descricao de formato).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.DSC_FC_PRIORITY     IS 'Prioridade da candidatura de formato: high, medium ou low.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.DSC_FC_DESCRIPTION  IS 'Descricao textual da regra de conformidade aplicavel.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.SIT_RED_CANDIDATE   IS 'Candidata a metrica de redundancia (Y/N).';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.DSC_RED_METRIC      IS 'Nome da metrica de redundancia aplicavel.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.DSC_RED_DIMENSION   IS 'Dimensao de qualidade da metrica de redundancia.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.TIP_RED_RULE        IS 'Tipo de regra de redundancia.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.DSC_RED_PRIORITY    IS 'Prioridade da candidatura de redundancia.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.DSC_RED_DESCRIPTION IS 'Descricao da candidatura a deteccao de redundancia.';
COMMENT ON COLUMN DQ_SCHEMA_METADATA.DSC_RED_CALC_METHOD IS 'Metodo de calculo (ex: METADATA_STATISTICS, DATA_SCAN_REQUIRED).';

CREATE INDEX IDX_SM_EXEC        ON DQ_SCHEMA_METADATA (COD_EXECUTION);
CREATE INDEX IDX_SM_OWNER_TABLE ON DQ_SCHEMA_METADATA (DSC_OWNER, NOM_TABLE);
CREATE INDEX IDX_SM_FC_CAND     ON DQ_SCHEMA_METADATA (SIT_FC_CANDIDATE);
CREATE INDEX IDX_SM_RED_CAND    ON DQ_SCHEMA_METADATA (SIT_RED_CANDIDATE);


-- ----------------------------------------------------------
-- 2. DQ_RULE_CANDIDATES
--    Aba DATA_QUALITY_RULE_CANDIDATES.
--    Lista consolidada de colunas candidatas a execucao
--    de metricas de qualidade.
-- ----------------------------------------------------------
CREATE TABLE DQ_RULE_CANDIDATES (
    COD_ID              NUMBER        GENERATED BY DEFAULT AS IDENTITY,
    COD_EXECUTION       NUMBER        NOT NULL,
    DSC_OWNER           VARCHAR2(128) NOT NULL,
    NOM_TABLE           VARCHAR2(128) NOT NULL,
    NOM_COLUMN          VARCHAR2(128) NOT NULL,
    TIP_DATA            VARCHAR2(50),
    DSC_METRIC          VARCHAR2(100) NOT NULL,
    DSC_DIMENSION       VARCHAR2(50)  NOT NULL,
    DSC_SEMANTIC_TAG    VARCHAR2(50),
    TIP_RULE            VARCHAR2(50)  NOT NULL,
    DSC_EXPECTED_FORMAT VARCHAR2(500),
    DSC_PRIORITY        VARCHAR2(20)  NOT NULL,
    DSC_DESCRIPTION     VARCHAR2(500),
    DSC_CALC_METHOD     VARCHAR2(50)  NOT NULL,
    NUM_ROWS            NUMBER(18),
    NUM_NULLS           NUMBER(18),
    NUM_DISTINCT        NUMBER(18),

    CONSTRAINT PK_RC
        PRIMARY KEY (COD_ID),
    CONSTRAINT FK_RC_EXEC
        FOREIGN KEY (COD_EXECUTION) REFERENCES DQ_EXECUTION(COD_EXECUTION),
    CONSTRAINT UQ_RC_COLUMN_METRIC
        UNIQUE (COD_EXECUTION, DSC_OWNER, NOM_TABLE, NOM_COLUMN, DSC_METRIC)
);

COMMENT ON TABLE  DQ_RULE_CANDIDATES                     IS 'Colunas candidatas a execucao de metricas de qualidade de dados.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.COD_ID              IS 'Identificador unico do registro (PK surrogate).';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.COD_EXECUTION       IS 'Referencia a execucao que gerou este registro.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.DSC_OWNER           IS 'Schema Oracle dono da tabela.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.NOM_TABLE           IS 'Nome da tabela.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.NOM_COLUMN          IS 'Nome da coluna candidata.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.TIP_DATA            IS 'Tipo de dado Oracle da coluna.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.DSC_METRIC          IS 'Nome da metrica de qualidade a ser calculada.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.DSC_DIMENSION       IS 'Dimensao de qualidade associada a metrica.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.DSC_SEMANTIC_TAG    IS 'Tag semantica detectada (ex: CPF, EMAIL, CEP).';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.TIP_RULE            IS 'Tipo da regra de validacao (ex: regex, date_string, duplicate_ratio).';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.DSC_EXPECTED_FORMAT IS 'Padrao esperado para validacao da coluna.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.DSC_PRIORITY        IS 'Prioridade de execucao: high, medium ou low.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.DSC_DESCRIPTION     IS 'Descricao da regra de candidatura.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.DSC_CALC_METHOD     IS 'Metodo de calculo: METADATA_STATISTICS ou DATA_SCAN_REQUIRED.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.NUM_ROWS            IS 'Numero de linhas da tabela no momento da candidatura.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.NUM_NULLS           IS 'Numero de valores nulos na coluna.';
COMMENT ON COLUMN DQ_RULE_CANDIDATES.NUM_DISTINCT        IS 'Numero de valores distintos na coluna.';

CREATE INDEX IDX_RC_EXEC        ON DQ_RULE_CANDIDATES (COD_EXECUTION);
CREATE INDEX IDX_RC_OWNER_TABLE ON DQ_RULE_CANDIDATES (DSC_OWNER, NOM_TABLE);
CREATE INDEX IDX_RC_PRIORITY    ON DQ_RULE_CANDIDATES (DSC_PRIORITY);
CREATE INDEX IDX_RC_CALC_METHOD ON DQ_RULE_CANDIDATES (DSC_CALC_METHOD);


-- ----------------------------------------------------------
-- 3. DQ_METADATA_MEASURES
--    Aba METADATA_MEASURES.
--    Medidas brutas calculadas sobre os metadados do schema.
-- ----------------------------------------------------------
CREATE TABLE DQ_METADATA_MEASURES (
    COD_ID          NUMBER        GENERATED BY DEFAULT AS IDENTITY,
    COD_EXECUTION   NUMBER        NOT NULL,
    COD_INDICATOR   VARCHAR2(20)  NOT NULL,
    DSC_CATEGORY    VARCHAR2(20)  NOT NULL,
    DSC_DESCRIPTION VARCHAR2(500),
    NUM_VALUE       NUMBER(18,4),

    CONSTRAINT PK_MM
        PRIMARY KEY (COD_ID),
    CONSTRAINT FK_MM_EXEC
        FOREIGN KEY (COD_EXECUTION) REFERENCES DQ_EXECUTION(COD_EXECUTION),
    CONSTRAINT UQ_MM_INDICATOR
        UNIQUE (COD_EXECUTION, COD_INDICATOR)
);

COMMENT ON TABLE  DQ_METADATA_MEASURES                IS 'Medidas calculadas sobre os metadados do schema (ex: total de tabelas, colunas, PKs).';
COMMENT ON COLUMN DQ_METADATA_MEASURES.COD_ID         IS 'Identificador unico do registro (PK surrogate).';
COMMENT ON COLUMN DQ_METADATA_MEASURES.COD_EXECUTION  IS 'Referencia a execucao que gerou este registro.';
COMMENT ON COLUMN DQ_METADATA_MEASURES.COD_INDICATOR  IS 'Codigo do indicador de medida (ex: MQME001).';
COMMENT ON COLUMN DQ_METADATA_MEASURES.DSC_CATEGORY   IS 'Categoria da medida (ex: RAW).';
COMMENT ON COLUMN DQ_METADATA_MEASURES.DSC_DESCRIPTION IS 'Descricao textual da medida.';
COMMENT ON COLUMN DQ_METADATA_MEASURES.NUM_VALUE      IS 'Valor calculado da medida.';

CREATE INDEX IDX_MM_EXEC ON DQ_METADATA_MEASURES (COD_EXECUTION);


-- ----------------------------------------------------------
-- 4. DQ_METADATA_ISSUES
--    Aba METADATA_ISSUES.
--    Problemas de qualidade identificados na camada de
--    metadados, com sugestoes de correcao.
-- ----------------------------------------------------------
CREATE TABLE DQ_METADATA_ISSUES (
    COD_ID                   NUMBER        GENERATED BY DEFAULT AS IDENTITY,
    COD_EXECUTION            NUMBER        NOT NULL,
    COD_RULE                 VARCHAR2(20)  NOT NULL,
    DSC_DESCRIPTION          VARCHAR2(500),
    DSC_OWNER                VARCHAR2(128) NOT NULL,
    NOM_TABLE                VARCHAR2(128) NOT NULL,
    NOM_COLUMN               VARCHAR2(128),
    NOM_CONSTRAINT           VARCHAR2(128),
    NUM_LENGTH               NUMBER(10),
    DSC_LENGTH_LIMIT         VARCHAR2(50),
    TIP_DATA                 VARCHAR2(50),
    TIP_COLUMN               VARCHAR2(50),
    DSC_SUGGESTED_VALUE      VARCHAR2(200),
    DSC_SUGGESTED_SOURCE     VARCHAR2(50),
    NUM_SUGGESTED_CONFIDENCE NUMBER(4,2),
    TXT_SUGGESTED_DDL        VARCHAR2(4000),
    TXT_SUGGESTED_DETAIL     VARCHAR2(4000),

    CONSTRAINT PK_MI
        PRIMARY KEY (COD_ID),
    CONSTRAINT FK_MI_EXEC
        FOREIGN KEY (COD_EXECUTION) REFERENCES DQ_EXECUTION(COD_EXECUTION)
);

COMMENT ON TABLE  DQ_METADATA_ISSUES                         IS 'Problemas de qualidade nos metadados com sugestoes de correcao.';
COMMENT ON COLUMN DQ_METADATA_ISSUES.COD_ID                  IS 'Identificador unico do registro (PK surrogate).';
COMMENT ON COLUMN DQ_METADATA_ISSUES.COD_EXECUTION           IS 'Referencia a execucao que gerou este registro.';
COMMENT ON COLUMN DQ_METADATA_ISSUES.COD_RULE                IS 'Codigo da regra violada (ex: MQME012).';
COMMENT ON COLUMN DQ_METADATA_ISSUES.DSC_DESCRIPTION         IS 'Descricao legivel da regra violada.';
COMMENT ON COLUMN DQ_METADATA_ISSUES.DSC_OWNER               IS 'Schema Oracle dono da tabela com o problema.';
COMMENT ON COLUMN DQ_METADATA_ISSUES.NOM_TABLE               IS 'Nome da tabela com o problema.';
COMMENT ON COLUMN DQ_METADATA_ISSUES.NOM_COLUMN              IS 'Nome da coluna com o problema (nulo se o problema e de tabela).';
COMMENT ON COLUMN DQ_METADATA_ISSUES.NOM_CONSTRAINT          IS 'Nome da constraint relacionada ao problema.';
COMMENT ON COLUMN DQ_METADATA_ISSUES.NUM_LENGTH              IS 'Comprimento atual da coluna, quando relevante.';
COMMENT ON COLUMN DQ_METADATA_ISSUES.DSC_LENGTH_LIMIT        IS 'Limite recomendado de comprimento.';
COMMENT ON COLUMN DQ_METADATA_ISSUES.TIP_DATA                IS 'Tipo de dado atual da coluna.';
COMMENT ON COLUMN DQ_METADATA_ISSUES.TIP_COLUMN              IS 'Tipo de coluna inferido pelo framework.';
COMMENT ON COLUMN DQ_METADATA_ISSUES.DSC_SUGGESTED_VALUE     IS 'Valor sugerido para correcao do problema.';
COMMENT ON COLUMN DQ_METADATA_ISSUES.DSC_SUGGESTED_SOURCE    IS 'Fonte da sugestao (ex: RULES, LLM_ERROR).';
COMMENT ON COLUMN DQ_METADATA_ISSUES.NUM_SUGGESTED_CONFIDENCE IS 'Grau de confianca da sugestao (0 a 1).';
COMMENT ON COLUMN DQ_METADATA_ISSUES.TXT_SUGGESTED_DDL       IS 'Comando DDL sugerido para corrigir o problema.';
COMMENT ON COLUMN DQ_METADATA_ISSUES.TXT_SUGGESTED_DETAIL    IS 'Detalhes adicionais sobre a sugestao ou erro na geracao.';

CREATE INDEX IDX_MI_EXEC        ON DQ_METADATA_ISSUES (COD_EXECUTION);
CREATE INDEX IDX_MI_RULE        ON DQ_METADATA_ISSUES (COD_EXECUTION, COD_RULE);
CREATE INDEX IDX_MI_OWNER_TABLE ON DQ_METADATA_ISSUES (DSC_OWNER, NOM_TABLE);


-- ----------------------------------------------------------
-- 5. DQ_DATA_ISSUES
--    Aba DATA_ISSUES.
--    Problemas de qualidade no conteudo real das tabelas.
--    Aba vazia na versao atual - preenchida nas proximas
--    fases do framework (validacao de dados).
-- ----------------------------------------------------------
CREATE TABLE DQ_DATA_ISSUES (
    COD_ID          NUMBER        GENERATED BY DEFAULT AS IDENTITY,
    COD_EXECUTION   NUMBER        NOT NULL,
    COD_RULE        VARCHAR2(20)  NOT NULL,
    DSC_DESCRIPTION VARCHAR2(500),
    DSC_OWNER       VARCHAR2(128) NOT NULL,
    NOM_TABLE       VARCHAR2(128) NOT NULL,
    NOM_COLUMN      VARCHAR2(128),
    TXT_VALUE       VARCHAR2(4000),

    CONSTRAINT PK_DI
        PRIMARY KEY (COD_ID),
    CONSTRAINT FK_DI_EXEC
        FOREIGN KEY (COD_EXECUTION) REFERENCES DQ_EXECUTION(COD_EXECUTION)
);

COMMENT ON TABLE  DQ_DATA_ISSUES                IS 'Problemas de qualidade no conteudo real das tabelas. Preenchida nas fases de validacao de dados.';
COMMENT ON COLUMN DQ_DATA_ISSUES.COD_ID         IS 'Identificador unico do registro (PK surrogate).';
COMMENT ON COLUMN DQ_DATA_ISSUES.COD_EXECUTION  IS 'Referencia a execucao que gerou este registro.';
COMMENT ON COLUMN DQ_DATA_ISSUES.COD_RULE       IS 'Codigo da regra de qualidade violada.';
COMMENT ON COLUMN DQ_DATA_ISSUES.DSC_DESCRIPTION IS 'Descricao legivel da regra violada.';
COMMENT ON COLUMN DQ_DATA_ISSUES.DSC_OWNER      IS 'Schema Oracle dono da tabela com o problema.';
COMMENT ON COLUMN DQ_DATA_ISSUES.NOM_TABLE      IS 'Nome da tabela com o problema.';
COMMENT ON COLUMN DQ_DATA_ISSUES.NOM_COLUMN     IS 'Nome da coluna com o problema.';
COMMENT ON COLUMN DQ_DATA_ISSUES.TXT_VALUE      IS 'Valor problematico encontrado nos dados.';

CREATE INDEX IDX_DI_EXEC        ON DQ_DATA_ISSUES (COD_EXECUTION);
CREATE INDEX IDX_DI_RULE        ON DQ_DATA_ISSUES (COD_EXECUTION, COD_RULE);
CREATE INDEX IDX_DI_OWNER_TABLE ON DQ_DATA_ISSUES (DSC_OWNER, NOM_TABLE);


-- ----------------------------------------------------------
-- 6. DQ_METRICS
--    Aba METRICS.
--    Indicadores consolidados de qualidade por dimensao,
--    calculados ao final de cada execucao.
-- ----------------------------------------------------------
CREATE TABLE DQ_METRICS (
    COD_ID          NUMBER        GENERATED BY DEFAULT AS IDENTITY,
    COD_EXECUTION   NUMBER        NOT NULL,
    COD_INDICATOR   VARCHAR2(20)  NOT NULL,
    DSC_DIMENSION   VARCHAR2(50),
    DSC_DESCRIPTION VARCHAR2(500),
    NUM_VALUE       NUMBER(10,4),

    CONSTRAINT PK_MET
        PRIMARY KEY (COD_ID),
    CONSTRAINT FK_MET_EXEC
        FOREIGN KEY (COD_EXECUTION) REFERENCES DQ_EXECUTION(COD_EXECUTION),
    CONSTRAINT UQ_MET_INDICATOR
        UNIQUE (COD_EXECUTION, COD_INDICATOR)
);

COMMENT ON TABLE  DQ_METRICS                 IS 'Indicadores consolidados de qualidade por dimensao ao final de cada execucao.';
COMMENT ON COLUMN DQ_METRICS.COD_ID          IS 'Identificador unico do registro (PK surrogate).';
COMMENT ON COLUMN DQ_METRICS.COD_EXECUTION   IS 'Referencia a execucao que gerou este registro.';
COMMENT ON COLUMN DQ_METRICS.COD_INDICATOR   IS 'Codigo do indicador de qualidade (ex: MQID001).';
COMMENT ON COLUMN DQ_METRICS.DSC_DIMENSION   IS 'Dimensao de qualidade do indicador (ex: Consistency, Completeness).';
COMMENT ON COLUMN DQ_METRICS.DSC_DESCRIPTION IS 'Descricao textual do indicador.';
COMMENT ON COLUMN DQ_METRICS.NUM_VALUE       IS 'Valor calculado do indicador (escala 0 a 100).';

CREATE INDEX IDX_MET_EXEC      ON DQ_METRICS (COD_EXECUTION);
CREATE INDEX IDX_MET_DIMENSION ON DQ_METRICS (DSC_DIMENSION);


-- ============================================================
-- FIM DO SCRIPT
-- ============================================================
-- Tabelas criadas (todos os nomes de coluna <= 30 caracteres):
--
--   DQ_EXECUTION           7 colunas  - Controle de execucoes
--   DQ_SCHEMA_METADATA    39 colunas  - Metadados estruturais
--   DQ_RULE_CANDIDATES    17 colunas  - Candidatos a metricas
--   DQ_METADATA_MEASURES   6 colunas  - Medidas sobre metadados
--   DQ_METADATA_ISSUES    17 colunas  - Problemas em metadados
--   DQ_DATA_ISSUES         8 colunas  - Problemas nos dados
--   DQ_METRICS             6 colunas  - Indicadores consolidados
-- ============================================================
