-- ============================================================
-- DDL: Objetos do framework de qualidade de dados
-- Schema/Owner: "sitram2" (DESE)
-- Executar conectado como QUALIDADE_DADOS ou DBA que
-- crie os objetos nesse schema.
-- ============================================================

-- ------------------------------------------------------------
-- Domínio de dimensões de qualidade
-- ------------------------------------------------------------
CREATE TABLE QUALIDADE_DADOS.DIMENSAO (
    COD_DIMENSAO   NUMBER        NOT NULL,
    DSC_DIMENSAO   VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_DIMENSAO PRIMARY KEY (COD_DIMENSAO),
    CONSTRAINT UK_DIMENSAO_DSC UNIQUE (DSC_DIMENSAO)
);

INSERT INTO QUALIDADE_DADOS.DIMENSAO (COD_DIMENSAO, DSC_DIMENSAO) VALUES (1, 'Consistency');
INSERT INTO QUALIDADE_DADOS.DIMENSAO (COD_DIMENSAO, DSC_DIMENSAO) VALUES (2, 'Completeness');
INSERT INTO QUALIDADE_DADOS.DIMENSAO (COD_DIMENSAO, DSC_DIMENSAO) VALUES (3, 'Uniqueness');
INSERT INTO QUALIDADE_DADOS.DIMENSAO (COD_DIMENSAO, DSC_DIMENSAO) VALUES (4, 'Conformity');
INSERT INTO QUALIDADE_DADOS.DIMENSAO (COD_DIMENSAO, DSC_DIMENSAO) VALUES (5, 'Accuracy');
COMMIT;

-- ------------------------------------------------------------
-- Registro de execuções
-- ------------------------------------------------------------
CREATE SEQUENCE QUALIDADE_DADOS.SQ_EXECUCAO
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE QUALIDADE_DADOS.EXECUCAO (
    SEQ_EXECUCAO     NUMBER        NOT NULL,
    DSC_OWNER        VARCHAR2(128),
    TIP_FONTE        VARCHAR2(20),
    STA_EXECUCAO     VARCHAR2(20)  NOT NULL,
    DAT_EXECUCAO     TIMESTAMP     NOT NULL,
    DAT_FINALIZACAO  TIMESTAMP,
    DSC_OBSERVACAO   VARCHAR2(4000),
    CONSTRAINT PK_EXECUCAO PRIMARY KEY (SEQ_EXECUCAO),
    CONSTRAINT CK_EXECUCAO_STA CHECK (STA_EXECUCAO IN ('RUNNING', 'SUCCESS', 'ERROR'))
);

-- ------------------------------------------------------------
-- Scores de qualidade (MDDQ / DDQ / SCHEMA_SCORE por indicador)
-- ------------------------------------------------------------
CREATE SEQUENCE QUALIDADE_DADOS.SQ_RESULTADO_QUALIDADE
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE QUALIDADE_DADOS.RESULTADO_QUALIDADE (
    SEQ_RESULTADO_QUALIDADE  NUMBER        NOT NULL,
    SEQ_EXECUCAO             NUMBER        NOT NULL,
    COD_MEDIDA               VARCHAR2(10),
    COD_DIMENSAO             NUMBER,
    TIP_RESULTADO            VARCHAR2(20),
    DSC_RESULTADO            VARCHAR2(400),
    NUM_PESO                 NUMBER(10,4),
    NUM_VALOR                NUMBER(10,4),
    CONSTRAINT PK_RESULTADO_QUALIDADE PRIMARY KEY (SEQ_RESULTADO_QUALIDADE),
    CONSTRAINT FK_RESULTADO_EXECUCAO  FOREIGN KEY (SEQ_EXECUCAO)  REFERENCES QUALIDADE_DADOS.EXECUCAO  (SEQ_EXECUCAO),
    CONSTRAINT FK_RESULTADO_DIMENSAO  FOREIGN KEY (COD_DIMENSAO)  REFERENCES QUALIDADE_DADOS.DIMENSAO  (COD_DIMENSAO)
);

-- ------------------------------------------------------------
-- Problemas encontrados (CPF / CNPJ / CGF inválidos)
-- ------------------------------------------------------------
CREATE SEQUENCE QUALIDADE_DADOS.SQ_PROBLEMA_EXECUCAO
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE QUALIDADE_DADOS.PROBLEMA_EXECUCAO (
    SEQ_PROBLEMA_EXECUCAO  NUMBER        NOT NULL,
    SEQ_EXECUCAO           NUMBER        NOT NULL,
    COD_MEDIDA             VARCHAR2(10),
    COD_DIMENSAO           NUMBER,
    DSC_PROBLEMA           VARCHAR2(200),
    DSC_OWNER              VARCHAR2(128),
    NOM_TABELA             VARCHAR2(128),
    NOM_COLUNA             VARCHAR2(128),
    DSC_VALOR              VARCHAR2(30),
    CONSTRAINT PK_PROBLEMA_EXECUCAO PRIMARY KEY (SEQ_PROBLEMA_EXECUCAO),
    CONSTRAINT FK_PROBLEMA_EXECUCAO  FOREIGN KEY (SEQ_EXECUCAO)  REFERENCES QUALIDADE_DADOS.EXECUCAO (SEQ_EXECUCAO),
    CONSTRAINT FK_PROBLEMA_DIMENSAO  FOREIGN KEY (COD_DIMENSAO)  REFERENCES QUALIDADE_DADOS.DIMENSAO (COD_DIMENSAO)
);
